### PR TITLE
Fixes automerge PR #66

### PR DESCRIPTION
**Pull request by denizzzka**

### CODE REVIEW

**Comment by kinke** [comment]
As already mentioned, these changes should be targeted at upstream Phobos, it's not LDC-specific and equally useful for GDC. So if you want to fix this, please cherry-pick my commit onto upstream, add the comment requested by Joakim and open an upstream PR.

**Comment by denizzzka** [comment]
Almost done:
https://github.com/dlang/phobos/pull/7362

**Comment by denizzzka** [comment]
(This comment moved from https://github.com/dlang/phobos/pull/7362#issuecomment-577708365)

> please get rid of all version (LDC) stuff

@kinke It cannot go on forever. Is it possible to implement assembler support in LDC in same manner as in DMD? We don’t have to keep copies of assembler snippets for DMD and for LDC at least for x86. In addition, there is another compiler (gdc) that could also use these snippets.

**Comment by kinke** [comment]
Why would you worry about that? It's already in there in LDC's fork and doesn't need to be touched. In addition, LDC does support DMD-style inline asm with some restrictions (and its own versions of inline asm + IR); GDC doesn't and has its own syntax. `std.math` is heavily customized by both LDC and GDC; the upstream version doesn't have any other compiler specifics. Once it's merged upstream, I'll take care of any arising merge conflicts.

**Comment by denizzzka** [comment]
> Why would you worry about that?

Just wanted to avoid future work on the continuous maintenance of the fork std.math for LDC.

> the upstream version doesn't have any other compiler specifics

x86 asm snippets can become different for DMD and LDC due to different version sections

**Pull request closed without merging**
